# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0096526f83edd9cab3b9fc2daa501da48dffcbcd6f3ec2580c7d1164ce704107f493e4f724a9ce243dbb4bcd7d6993f93ecb580d7c7cc4798e82c8ca25b7075c

test:
  secret_key_base: 830793b1d8bdd28f6b59db6d7d75bf569a458633491de94f15fe6c88600523020da85d75324fb65b18330cadf1e4bc8474e899ded259f34d0ad0c33001757ee9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
